### ISSUE TITLE
Linux instructions???

### ISSUE THREAD

**Issue by mercertom** [CHEF-KOCH/HowTo-flash-Intel-Management-Engine-ME-firmware#1]
`The flashing process is easy peasy, call FWUpdLcl64.exe -FORCERESET -F ME_my_firmware.bin (make sure you replace ME_my_firmware.bin with the correct firmware name you downloaded!).`

This does nothing on Linux. How does one flash IME on Linux? Please add Linux instructions to the README.

**Comment by CHEF-KOCH** [comment]
There is no tool for Linux, which means you cannot flash it under Linux. 

Linux itself gets patches via Kernel updates and it is not needed to install an firmware upgrade manually.

**Comment by mercertom** [comment]
OK. Then delete the mentions of Linux from this. For example, in requirements.

```
Requirements
Windows/Linux
```
